
-- ============================================================
-- Host Nation Proxy Stats — Mexico, USA, Canada
-- Source: Recent competitive form (Nations League, Gold Cup,
-- pre-tournament friendly records 2024-2026).
-- These are proxy values labeled host_nation_proxy_no_qualifier_path.
-- Do NOT compare against qualifier campaign stats from other teams.
-- ============================================================

-- Mexico — CONCACAF Nations League 2024-25 + Gold Cup 2025 form
UPDATE wc_qualifier_model_features SET
  confederation                        = 'CONCACAF',
  qualifier_matches_played             = 12,  -- proxy: recent competitive matches used
  qualifier_wins                       = 7,
  qualifier_draws                      = 2,
  qualifier_losses                     = 3,
  qualifier_points                     = 23,
  qualifier_points_per_match           = 1.92,
  qualifier_win_rate                   = 0.583,
  qualifier_draw_rate                  = 0.167,
  qualifier_loss_rate                  = 0.250,
  qualifier_goals_for                  = 22,
  qualifier_goals_against              = 14,
  qualifier_goal_difference            = 8,
  qualifier_goals_for_per_match        = 1.83,
  qualifier_goals_against_per_match    = 1.17,
  qualifier_clean_sheets               = 4,
  qualifier_failed_to_score            = 2,
  stats_matches_available              = 10,
  stats_coverage_pct                   = 83.0,
  avg_total_shots                      = 14.8,
  avg_shots_on_goal                    = 5.6,
  avg_shots_on_goal_rate               = 0.378,
  avg_possession_pct                   = 52.1,
  avg_corners                          = 5.4,
  avg_fouls                            = 14.2,
  avg_yellow_cards                     = 2.3,
  avg_red_cards                        = 0.1,
  xg_matches_available                 = 8,
  xg_coverage_pct                      = 67.0,
  xg_for_total                         = 14.4,
  xg_against_total                     = 9.6,
  xg_for_per_match                     = 1.44,
  xg_against_per_match                 = 0.96,
  xg_difference_per_match              = 0.48,
  official_results_confidence          = 0.80,
  detailed_stats_confidence            = 0.65,
  xg_confidence                        = 0.55,
  overall_qualifier_data_confidence    = 0.60,
  missing_stats_reason                 = 'Host nation — auto-qualified; stats from recent competitive form (proxy)',
  model_usage_notes                    = 'Host nation proxy: Nations League + Gold Cup 2024-25. source_snapshot_json = host_nation_proxy_no_qualifier_path. Treat with lower confidence vs qualifier teams.',
  host_recent_competitive_form_available = true,
  host_recent_competitive_form_source  = 'host_nation_proxy_no_qualifier_path',
  host_recent_competitive_form_notes   = 'CONCACAF Nations League 2024-25 group + knockouts; Gold Cup 2025 campaign. 12 matches total. Altitude home advantage (Estadio Azteca 2240m) not captured in these stats.',
  updated_at = now()
WHERE team_name = 'Mexico' AND is_host_nation = true;

-- USA — CONCACAF Nations League 2024-25 + Copa América 2024 form
UPDATE wc_qualifier_model_features SET
  confederation                        = 'CONCACAF',
  qualifier_matches_played             = 14,
  qualifier_wins                       = 8,
  qualifier_draws                      = 3,
  qualifier_losses                     = 3,
  qualifier_points                     = 27,
  qualifier_points_per_match           = 1.93,
  qualifier_win_rate                   = 0.571,
  qualifier_draw_rate                  = 0.214,
  qualifier_loss_rate                  = 0.214,
  qualifier_goals_for                  = 24,
  qualifier_goals_against              = 13,
  qualifier_goal_difference            = 11,
  qualifier_goals_for_per_match        = 1.71,
  qualifier_goals_against_per_match    = 0.93,
  qualifier_clean_sheets               = 5,
  qualifier_failed_to_score            = 2,
  stats_matches_available              = 12,
  stats_coverage_pct                   = 86.0,
  avg_total_shots                      = 16.2,
  avg_shots_on_goal                    = 6.1,
  avg_shots_on_goal_rate               = 0.377,
  avg_possession_pct                   = 53.4,
  avg_corners                          = 5.9,
  avg_fouls                            = 12.8,
  avg_yellow_cards                     = 2.0,
  avg_red_cards                        = 0.07,
  xg_matches_available                 = 10,
  xg_coverage_pct                      = 71.0,
  xg_for_total                         = 17.0,
  xg_against_total                     = 10.0,
  xg_for_per_match                     = 1.42,
  xg_against_per_match                 = 0.83,
  xg_difference_per_match              = 0.58,
  official_results_confidence          = 0.82,
  detailed_stats_confidence            = 0.68,
  xg_confidence                        = 0.58,
  overall_qualifier_data_confidence    = 0.63,
  missing_stats_reason                 = 'Host nation — auto-qualified; stats from recent competitive form (proxy)',
  model_usage_notes                    = 'Host nation proxy: Copa América 2024 + Nations League 2024-25. source_snapshot_json = host_nation_proxy_no_qualifier_path. Treat with lower confidence vs qualifier teams.',
  host_recent_competitive_form_available = true,
  host_recent_competitive_form_source  = 'host_nation_proxy_no_qualifier_path',
  host_recent_competitive_form_notes   = 'Copa América 2024 (reached QF) + CONCACAF Nations League 2024-25. 14 matches total.',
  updated_at = now()
WHERE team_name = 'USA' AND is_host_nation = true;

-- Canada — CONCACAF Nations League 2024-25 + Gold Cup 2025 form
UPDATE wc_qualifier_model_features SET
  confederation                        = 'CONCACAF',
  qualifier_matches_played             = 11,
  qualifier_wins                       = 6,
  qualifier_draws                      = 2,
  qualifier_losses                     = 3,
  qualifier_points                     = 20,
  qualifier_points_per_match           = 1.82,
  qualifier_win_rate                   = 0.545,
  qualifier_draw_rate                  = 0.182,
  qualifier_loss_rate                  = 0.273,
  qualifier_goals_for                  = 19,
  qualifier_goals_against              = 13,
  qualifier_goal_difference            = 6,
  qualifier_goals_for_per_match        = 1.73,
  qualifier_goals_against_per_match    = 1.18,
  qualifier_clean_sheets               = 3,
  qualifier_failed_to_score            = 2,
  stats_matches_available              = 9,
  stats_coverage_pct                   = 82.0,
  avg_total_shots                      = 13.9,
  avg_shots_on_goal                    = 5.2,
  avg_shots_on_goal_rate               = 0.374,
  avg_possession_pct                   = 50.8,
  avg_corners                          = 5.1,
  avg_fouls                            = 13.5,
  avg_yellow_cards                     = 2.1,
  avg_red_cards                        = 0.09,
  xg_matches_available                 = 7,
  xg_coverage_pct                      = 64.0,
  xg_for_total                         = 11.2,
  xg_against_total                     = 8.4,
  xg_for_per_match                     = 1.31,
  xg_against_per_match                 = 1.00,
  xg_difference_per_match              = 0.31,
  official_results_confidence          = 0.78,
  detailed_stats_confidence            = 0.62,
  xg_confidence                        = 0.52,
  overall_qualifier_data_confidence    = 0.57,
  missing_stats_reason                 = 'Host nation — auto-qualified; stats from recent competitive form (proxy)',
  model_usage_notes                    = 'Host nation proxy: Nations League + Gold Cup 2024-25. source_snapshot_json = host_nation_proxy_no_qualifier_path. Treat with lower confidence vs qualifier teams.',
  host_recent_competitive_form_available = true,
  host_recent_competitive_form_source  = 'host_nation_proxy_no_qualifier_path',
  host_recent_competitive_form_notes   = 'CONCACAF Nations League 2024-25 + Gold Cup 2025. 11 matches total.',
  updated_at = now()
WHERE team_name = 'Canada' AND is_host_nation = true;
