/*
  # Populate wch_teams iso2 and name_tr

  Backfills the `iso2` (ISO 3166-1 alpha-2 country code) and `name_tr` (Turkish name)
  columns for all distinct team names in wc_history.teams.

  - Covers all 87 distinct team names found in the dataset (1930–2022)
  - Historical/defunct nations get sensible iso2 codes (e.g. Soviet Union → su, West Germany → de)
  - Updates are keyed on name_en so they apply to all editions of each team
*/

UPDATE wc_history.teams SET
  iso2 = CASE name_en
    WHEN 'Algeria'              THEN 'dz'
    WHEN 'Angola'               THEN 'ao'
    WHEN 'Argentina'            THEN 'ar'
    WHEN 'Australia'            THEN 'au'
    WHEN 'Austria'              THEN 'at'
    WHEN 'Belgium'              THEN 'be'
    WHEN 'Bolivia'              THEN 'bo'
    WHEN 'Bosnia & Herzegovina' THEN 'ba'
    WHEN 'Brazil'               THEN 'br'
    WHEN 'Bulgaria'             THEN 'bg'
    WHEN 'Cameroon'             THEN 'cm'
    WHEN 'Canada'               THEN 'ca'
    WHEN 'Chile'                THEN 'cl'
    WHEN 'China'                THEN 'cn'
    WHEN 'Colombia'             THEN 'co'
    WHEN 'Costa Rica'           THEN 'cr'
    WHEN 'Côte d''Ivoire'       THEN 'ci'
    WHEN 'Croatia'              THEN 'hr'
    WHEN 'Cuba'                 THEN 'cu'
    WHEN 'Czech Republic'       THEN 'cz'
    WHEN 'Czechoslovakia'       THEN 'cz'
    WHEN 'Denmark'              THEN 'dk'
    WHEN 'Dutch East Indies'    THEN 'id'
    WHEN 'East Germany'         THEN 'de'
    WHEN 'Ecuador'              THEN 'ec'
    WHEN 'Egypt'                THEN 'eg'
    WHEN 'El Salvador'          THEN 'sv'
    WHEN 'England'              THEN 'gb-eng'
    WHEN 'France'               THEN 'fr'
    WHEN 'Germany'              THEN 'de'
    WHEN 'Ghana'                THEN 'gh'
    WHEN 'Greece'               THEN 'gr'
    WHEN 'Haiti'                THEN 'ht'
    WHEN 'Honduras'             THEN 'hn'
    WHEN 'Hungary'              THEN 'hu'
    WHEN 'Iceland'              THEN 'is'
    WHEN 'Iran'                 THEN 'ir'
    WHEN 'Iraq'                 THEN 'iq'
    WHEN 'Ireland'              THEN 'ie'
    WHEN 'Israel'               THEN 'il'
    WHEN 'Italy'                THEN 'it'
    WHEN 'Ivory Coast'          THEN 'ci'
    WHEN 'Jamaica'              THEN 'jm'
    WHEN 'Japan'                THEN 'jp'
    WHEN 'Kuwait'               THEN 'kw'
    WHEN 'Mexico'               THEN 'mx'
    WHEN 'Morocco'              THEN 'ma'
    WHEN 'Netherlands'          THEN 'nl'
    WHEN 'New Zealand'          THEN 'nz'
    WHEN 'Nigeria'              THEN 'ng'
    WHEN 'North Korea'          THEN 'kp'
    WHEN 'Northern Ireland'     THEN 'gb-nir'
    WHEN 'Norway'               THEN 'no'
    WHEN 'Panama'               THEN 'pa'
    WHEN 'Paraguay'             THEN 'py'
    WHEN 'Peru'                 THEN 'pe'
    WHEN 'Poland'               THEN 'pl'
    WHEN 'Portugal'             THEN 'pt'
    WHEN 'Qatar'                THEN 'qa'
    WHEN 'Romania'              THEN 'ro'
    WHEN 'Russia'               THEN 'ru'
    WHEN 'Saudi Arabia'         THEN 'sa'
    WHEN 'Scotland'             THEN 'gb-sct'
    WHEN 'Senegal'              THEN 'sn'
    WHEN 'Serbia'               THEN 'rs'
    WHEN 'Serbia and Montenegro' THEN 'rs'
    WHEN 'Slovakia'             THEN 'sk'
    WHEN 'Slovenia'             THEN 'si'
    WHEN 'South Africa'         THEN 'za'
    WHEN 'South Korea'          THEN 'kr'
    WHEN 'Soviet Union'         THEN 'su'
    WHEN 'Spain'                THEN 'es'
    WHEN 'Sweden'               THEN 'se'
    WHEN 'Switzerland'          THEN 'ch'
    WHEN 'Togo'                 THEN 'tg'
    WHEN 'Trinidad and Tobago'  THEN 'tt'
    WHEN 'Tunisia'              THEN 'tn'
    WHEN 'Turkey'               THEN 'tr'
    WHEN 'Ukraine'              THEN 'ua'
    WHEN 'United Arab Emirates' THEN 'ae'
    WHEN 'United States'        THEN 'us'
    WHEN 'Uruguay'              THEN 'uy'
    WHEN 'USA'                  THEN 'us'
    WHEN 'Wales'                THEN 'gb-wls'
    WHEN 'West Germany'         THEN 'de'
    WHEN 'Yugoslavia'           THEN 'rs'
    WHEN 'Zaire'                THEN 'cd'
    ELSE iso2
  END,
  name_tr = CASE name_en
    WHEN 'Algeria'              THEN 'Cezayir'
    WHEN 'Angola'               THEN 'Angola'
    WHEN 'Argentina'            THEN 'Arjantin'
    WHEN 'Australia'            THEN 'Avustralya'
    WHEN 'Austria'              THEN 'Avusturya'
    WHEN 'Belgium'              THEN 'Belçika'
    WHEN 'Bolivia'              THEN 'Bolivya'
    WHEN 'Bosnia & Herzegovina' THEN 'Bosna Hersek'
    WHEN 'Brazil'               THEN 'Brezilya'
    WHEN 'Bulgaria'             THEN 'Bulgaristan'
    WHEN 'Cameroon'             THEN 'Kamerun'
    WHEN 'Canada'               THEN 'Kanada'
    WHEN 'Chile'                THEN 'Şili'
    WHEN 'China'                THEN 'Çin'
    WHEN 'Colombia'             THEN 'Kolombiya'
    WHEN 'Costa Rica'           THEN 'Kosta Rika'
    WHEN 'Côte d''Ivoire'       THEN 'Fildişi Sahili'
    WHEN 'Croatia'              THEN 'Hırvatistan'
    WHEN 'Cuba'                 THEN 'Küba'
    WHEN 'Czech Republic'       THEN 'Çek Cumhuriyeti'
    WHEN 'Czechoslovakia'       THEN 'Çekoslovakya'
    WHEN 'Denmark'              THEN 'Danimarka'
    WHEN 'Dutch East Indies'    THEN 'Hollanda Doğu Hint Adaları'
    WHEN 'East Germany'         THEN 'Doğu Almanya'
    WHEN 'Ecuador'              THEN 'Ekvador'
    WHEN 'Egypt'                THEN 'Mısır'
    WHEN 'El Salvador'          THEN 'El Salvador'
    WHEN 'England'              THEN 'İngiltere'
    WHEN 'France'               THEN 'Fransa'
    WHEN 'Germany'              THEN 'Almanya'
    WHEN 'Ghana'                THEN 'Gana'
    WHEN 'Greece'               THEN 'Yunanistan'
    WHEN 'Haiti'                THEN 'Haiti'
    WHEN 'Honduras'             THEN 'Honduras'
    WHEN 'Hungary'              THEN 'Macaristan'
    WHEN 'Iceland'              THEN 'İzlanda'
    WHEN 'Iran'                 THEN 'İran'
    WHEN 'Iraq'                 THEN 'Irak'
    WHEN 'Ireland'              THEN 'İrlanda'
    WHEN 'Israel'               THEN 'İsrail'
    WHEN 'Italy'                THEN 'İtalya'
    WHEN 'Ivory Coast'          THEN 'Fildişi Sahili'
    WHEN 'Jamaica'              THEN 'Jamaika'
    WHEN 'Japan'                THEN 'Japonya'
    WHEN 'Kuwait'               THEN 'Kuveyt'
    WHEN 'Mexico'               THEN 'Meksika'
    WHEN 'Morocco'              THEN 'Fas'
    WHEN 'Netherlands'          THEN 'Hollanda'
    WHEN 'New Zealand'          THEN 'Yeni Zelanda'
    WHEN 'Nigeria'              THEN 'Nijerya'
    WHEN 'North Korea'          THEN 'Kuzey Kore'
    WHEN 'Northern Ireland'     THEN 'Kuzey İrlanda'
    WHEN 'Norway'               THEN 'Norveç'
    WHEN 'Panama'               THEN 'Panama'
    WHEN 'Paraguay'             THEN 'Paraguay'
    WHEN 'Peru'                 THEN 'Peru'
    WHEN 'Poland'               THEN 'Polonya'
    WHEN 'Portugal'             THEN 'Portekiz'
    WHEN 'Qatar'                THEN 'Katar'
    WHEN 'Romania'              THEN 'Romanya'
    WHEN 'Russia'               THEN 'Rusya'
    WHEN 'Saudi Arabia'         THEN 'Suudi Arabistan'
    WHEN 'Scotland'             THEN 'İskoçya'
    WHEN 'Senegal'              THEN 'Senegal'
    WHEN 'Serbia'               THEN 'Sırbistan'
    WHEN 'Serbia and Montenegro' THEN 'Sırbistan ve Karadağ'
    WHEN 'Slovakia'             THEN 'Slovakya'
    WHEN 'Slovenia'             THEN 'Slovenya'
    WHEN 'South Africa'         THEN 'Güney Afrika'
    WHEN 'South Korea'          THEN 'Güney Kore'
    WHEN 'Soviet Union'         THEN 'Sovyetler Birliği'
    WHEN 'Spain'                THEN 'İspanya'
    WHEN 'Sweden'               THEN 'İsveç'
    WHEN 'Switzerland'          THEN 'İsviçre'
    WHEN 'Togo'                 THEN 'Togo'
    WHEN 'Trinidad and Tobago'  THEN 'Trinidad ve Tobago'
    WHEN 'Tunisia'              THEN 'Tunus'
    WHEN 'Turkey'               THEN 'Türkiye'
    WHEN 'Ukraine'              THEN 'Ukrayna'
    WHEN 'United Arab Emirates' THEN 'Birleşik Arap Emirlikleri'
    WHEN 'United States'        THEN 'Amerika Birleşik Devletleri'
    WHEN 'Uruguay'              THEN 'Uruguay'
    WHEN 'USA'                  THEN 'Amerika Birleşik Devletleri'
    WHEN 'Wales'                THEN 'Galler'
    WHEN 'West Germany'         THEN 'Batı Almanya'
    WHEN 'Yugoslavia'           THEN 'Yugoslavya'
    WHEN 'Zaire'                THEN 'Zaire'
    ELSE name_tr
  END
WHERE iso2 IS NULL OR name_tr IS NULL;
